#!/bin/bash
export CYPRESS_FIND_URL=https://...
export CYPRESS_PUBLISH_URL=https://...
export CYPRESS_LEGACY_URL=https://...
export CYPRESS_LEGACY_USERNAME=...
export CYPRESS_LEGACY_PASSWORD=...
npx cypress open
